---
- block:
  - name: Check HTTP Server type
    shell: "curl -Is http://127.0.0.1 | grep 'Server' |awk -F ': ' '{print $2}'|tr 'A-Z' 'a-z'"
    register: http_type
    
  - name: Check whether the local machine contains MySQL
    shell: curl -Is 127.0.0.1:3306 > /dev/null;echo $?
    register: check_mysqlserver
  
  - name: Create apps directory
    file: 
        path: /data/apps
        state: directory
        owner: "{{http_type.stdout}}"
        group: "{{http_type.stdout}}"
        mode: 0755

  - name: Download phpMyAdmin
    unarchive:
      src: "{{phpmyadmin_download_url.old}}"
      dest: /data/apps
      remote_src: yes
    when: phpmyadmin_php_version <= "5.4"

  - name: Download phpMyAdmin
    unarchive:
      src: "{{phpmyadmin_download_url.new}}"
      dest: /data/apps
      remote_src: yes
    when: phpmyadmin_php_version > "5.5"

  - name: phpMyadmin directory rename
    shell: mv /data/apps/phpMyAdmin-* /data/apps/phpmyadmin
    ignore_errors: True
  
  - name: phpMyadmin Configuration
    copy: 
      src: config.inc.php
      dest: /data/apps/phpmyadmin/
  
  - block:
    - name: Active phpMyAdmin 4.0.x Advanced Features
      mysql_db:
        config_file: /etc/my.cnf
        login_user: root
        login_password: "{{phpmyadmin_mysql_password}}"
        name: phpmyadmin
        state: import
        target: /data/apps/phpmyadmin/examples/create_tables.sql
      when: phpmyadmin_php_version <= "5.4"

    - name: Active phpMyAdmin 4.x Advanced Features
      mysql_db:
        config_file: /etc/my.cnf
        login_user: root
        login_password: "{{phpmyadmin_mysql_password}}"
        name: phpmyadmin
        state: import
        target: /data/apps/phpmyadmin/sql/create_tables.sql
      when: phpmyadmin_php_version >= "5.5"
    when: check_mysqlserver.stdout == '0'


   
  - name: allow login to any user entered server in cookie based authentication 
    lineinfile:
      dest: /data/apps/phpmyadmin/libraries/config.default.php
      regexp: "$cfg['AllowArbitraryServer'] = false;"
      line: "$cfg['AllowArbitraryServer'] = true;"
      state: present
    when: check_mysqlserver.stdout > '0'

  - name: change phpMyadmin permission
    file: 
      path: /data/apps/phpmyadmin
      group: "{{http_type.stdout}}"
      owner: "{{http_type.stdout}}"
      recurse: yes
      state: directory
  
  - block: # phpMyAdmin Apache
    - name: Copy phpMyAdmin Configuration for apache
      copy: src=phpMyAdmin-apache.conf dest=/etc/httpd/conf.d/phpMyAdmin.conf
    
    - name: apache service restart
      service: name=httpd state=restarted

    when: http_type.stdout == 'apache'


  - block: # phpMyAdmin Nginx
    - name: Copy phpMyAdmin Configuration for nginx
      copy: src=phpMyAdmin-nginx.conf dest=/etc/nginx/extra/phpmyadmin.conf
      
    - name: apache service restart
      service: name=nginx state=restarted

    when: http_type.stdout == 'nginx'

  when: ansible_os_family == 'RedHat'

- debug: msg="Not Support Ubuntu"
  when: ansible_os_family == 'Debian'
