## 部署
- name: Nextcloud
  hosts: all
  become: yes
  become_method: sudo 
  vars_files:
    - vars/main.yml 
  vars_prompt:
    - name: 'webs_selection'
      prompt: "\nWhich Web-Server do you want to use? [ 1/2 ] \n\n
      1: Apache\n
      2: Nginx\n"
      private: no
      default: 1

    - name: 'onlyoffice_selection'
      prompt: "\nDo you want to install OnlyOffice documentserver? [ 1/2 ] \n\n
      1: Yes\n
      2: No\n"
      private: no
      default: 1

  vars:

    webs_select:
      '1': 'apache'
      '2': 'nginx'

    infrastructure_select:
      '1': 'LAMP'
      '2': 'LNMP'

    onlyoffice_select:
      '1': True
      '2': ''

    nextcloud_webs: "{{webs_select[webs_selection]}}" 
    nextcloud_onlyoffice: "{{onlyoffice_select[onlyoffice_selection]}}" 
    phpmyadmin_webs: "{{webs_select[webs_selection]}}" 
    w9panel_webs: "{{webs_select[webs_selection]}}" 
    w9panel_set_infrastructure: "{{infrastructure_select[webs_selection]}}" 
    w9panel_set_apps: 
      - NextCloud
  
  pre_tasks:
    - include_vars: roles/role_cloud/vars/cloud_download_url.yml
      when: region == '1' or region == 1

    - debug:
        msg: NextCloud will be installed on {{w9panel_set_infrastructure}}, OS is {{ansible_distribution}}, region code is {{region}}

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_apache, when: nextcloud_webs == 'apache', tags: "role_apache"}
    - {role: role_nginx, when: nextcloud_webs == 'nginx', tags: "role_nginx"}
    - {role: role_mysql, tags: "role_mysql"}
    - {role: role_php-fpm, tags: "role_php-fpm"}
    - {role: role_inotify_watch, tags: "role_inotify_watch"}
    - {role: role_lamp, when: nextcloud_webs == 'apache', tags: "role_lamp"}
    - {role: role_lnmp, when: nextcloud_webs == 'nginx', tags: "role_lnmp"}
    - {role: role_phpmyadmin, tags: "role_phpmyadmin"}
    - {role: role_9panel, tags: "role_9panel"}
    - {role: role_redis, tags: "role_redis"}
    - {role: role_docker, tags: "role_docker", when: nextcloud_onlyoffice}
    - {role: nextcloud, tags: "nextcloud"}
    - {role: role_init_password, tags: "role_init_password"}
    - {role: role_preend, preend_certbot: True, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
