# 根据需求添加相对应的role
- src: http://github.com/websoft9dev/role_common
  version: master

- src: http://github.com/websoft9dev/role_cloud
  version: master

- src: http://github.com/websoft9dev/role_apache
  version: master

- src: http://github.com/websoft9dev/role_redis
  version: master

- src: http://github.com/websoft9dev/role_nginx
  version: master  

- src: http://github.com/websoft9dev/role_mysql
  version: master

- src: http://github.com/websoft9dev/role_php
  version: master

- src: http://github.com/websoft9dev/role_inotify_watch
  version: master

- src: http://github.com/websoft9dev/role_init
  version: master
  
- src: http://github.com/websoft9dev/role_preend
  version: master

- src: http://github.com/websoft9dev/role_end
  version: master

- src: http://github.com/websoft9dev/role_docker
  version: master
 
- src: http://github.com/websoft9dev/role_9panel
  version: master
